import type { Config } from "tailwindcss";

const categorySafelist = [
  // Math — blue
  "bg-blue-100", "text-blue-600", "group-hover:bg-blue-200", "bg-blue-50", "text-blue-700",
  // Finance — green
  "bg-green-100", "text-green-600", "group-hover:bg-green-200", "bg-green-50", "text-green-700",
  // Fitness — red
  "bg-red-100", "text-red-600", "group-hover:bg-red-200", "bg-red-50", "text-red-700",
  // Text — amber
  "bg-amber-100", "text-amber-600", "group-hover:bg-amber-200", "bg-amber-50", "text-amber-700",
  // Design — purple
  "bg-purple-100", "text-purple-600", "group-hover:bg-purple-200", "bg-purple-50", "text-purple-700",
  // Converters — cyan
  "bg-cyan-100", "text-cyan-600", "group-hover:bg-cyan-200", "bg-cyan-50", "text-cyan-700",
  // Developer — gray
  "bg-gray-100", "text-gray-600", "group-hover:bg-gray-200", "bg-gray-50", "text-gray-700",
];

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx}",
    "./constants/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: categorySafelist,
  theme: {
    extend: {
      colors: {
        primary: "#ab3500",
        "primary-foreground": "#ffffff",
        "primary-container": "#ff6b35",
        "on-primary": "#ffffff",
        "on-primary-container": "#5f1900",
        secondary: "#0058be",
        "secondary-foreground": "#ffffff",
        "secondary-container": "#2170e4",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fefcff",
        tertiary: "#006c49",
        "tertiary-foreground": "#ffffff",
        "tertiary-container": "#00af79",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#003a25",
        surface: "#fcf8ff",
        "surface-bright": "#fcf8ff",
        "surface-dim": "#dad7f3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f2ff",
        "surface-container": "#efecff",
        "surface-container-high": "#e8e5ff",
        "surface-container-highest": "#e2e0fc",
        "surface-variant": "#e2e0fc",
        background: "#fcf8ff",
        foreground: "#1a1a2e",
        "on-background": "#1a1a2e",
        "on-surface": "#1a1a2e",
        "on-surface-variant": "#594139",
        outline: "#8d7168",
        "outline-variant": "#e1bfb5",
        "inverse-surface": "#2f2e43",
        "inverse-on-surface": "#f2efff",
        "inverse-primary": "#ffb59d",
        "primary-fixed": "#ffdbd0",
        "primary-fixed-dim": "#ffb59d",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        success: "#10B981",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        destructive: "var(--destructive)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        "2xl": "64px",
        gutter: "24px",
        "container-max": "1280px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        h1: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        h2: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        h3: ["var(--font-plus-jakarta)", "Plus Jakarta Sans", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        small: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        display: ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        h1: ["36px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h1-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        h2: ["28px", { lineHeight: "1.3", fontWeight: "600" }],
        h3: ["22px", { lineHeight: "1.4", fontWeight: "600" }],
        body: ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        small: ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        label: ["12px", { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
export default config;
