/** Per-tool UI strings for calculator / tool interfaces — used by generate scripts. */
export type ToolUiMap = Record<string, string>;

const sharedEn: ToolUiMap = {
  gender: "Gender",
  result: "Result",
  value: "Value",
  from: "From",
  to: "To",
  copy: "Copy",
  copied: "Copied",
  copyFailed: "Copy failed",
};

export const enToolUiMaps: Record<string, ToolUiMap> = {
  "simple-interest-calculator": {
    principal: "Principal",
    rate: "Rate (%)",
    timeYears: "Time (years)",
    yearShort: "yr",
    interestEarned: "Interest earned",
    totalAmount: "Total amount",
  },
  "compound-interest-calculator": {
    principal: "Principal",
    annualRate: "Annual rate (%)",
    timeYears: "Time (years)",
    compounding: "Compounding",
    totalAmount: "Total amount",
    totalInterest: "Total interest",
    yearByYearBreakdown: "Year-by-year breakdown",
    year: "Year",
    balance: "Balance",
    interestEarned: "Interest earned",
    frequencyAnnually: "Annually",
    frequencySemiannually: "Semi-annually",
    frequencyQuarterly: "Quarterly",
    frequencyMonthly: "Monthly",
    frequencyDaily: "Daily",
  },
  "emi-calculator": {
    loanAmount: "Loan amount",
    interestRate: "Interest rate (% per year)",
    tenure: "Tenure",
    monthlyEmi: "Monthly EMI",
    totalInterest: "Total interest",
    totalPayment: "Total payment",
    principalVsInterest: "Principal vs interest",
    principalPercent: "Principal {percent}%",
    interestPercent: "Interest {percent}%",
  },
  "bmi-calculator": {
    weight: "Weight",
    height: "Height",
    resultsAriaLabel: "BMI results",
    yourBmiIs: "Your BMI is",
    categoryUnderweight: "Underweight",
    categoryNormal: "Normal weight",
    categoryOverweight: "Overweight",
    categoryObese: "Obese",
  },
  "percentage-calculator": {
    tabOf: "X% of Y",
    tabWhatPercent: "X is what % of Y?",
    tabChange: "% change",
    labelPercentageX: "Percentage (X)",
    labelNumberY: "Number (Y)",
    labelNumberX: "Number (X)",
    labelFromX: "From (X)",
    labelToY: "To (Y)",
    resultOf: "{a}% of {b} is {value}",
    resultWhatPercent: "{a} is {value}% of {b}",
    resultChange: "Change from {a} to {b} is {value}%",
  },
  "discount-calculator": {
    originalPrice: "Original price",
    discountPercent: "Discount (%)",
    finalPrice: "Final price",
    youSave: "You save {amount}",
  },
  "average-calculator": {
    numbersInput: "Numbers",
    numbersPlaceholder: "Enter numbers separated by commas or new lines...",
    mean: "Mean",
    median: "Median",
    mode: "Mode",
    min: "Min",
    max: "Max",
    count: "Count",
    enterNumbers: "Enter at least one valid number to see results.",
  },
  "age-calculator": {
    dateOfBirth: "Date of birth",
    asOfDate: "As of date",
    yourAge: "Your age",
    years: "Years",
    months: "Months",
    days: "Days",
    livedSummary: "You've lived {days} days, or approximately {hours} hours.",
    invalidDateRange:
      "Please enter a valid birth date that is before the \"as of\" date.",
    nextBirthdayIn: "Next birthday in {days} days",
    nextBirthdayToday: "Happy birthday! Today is your birthday.",
    ageSummary: "{years} years, {months} months, {days} days",
  },
  "tip-calculator": {
    billAmount: "Bill amount",
    tipPercent: "Tip (%)",
    people: "People",
    tip: "Tip",
    total: "Total",
    perPerson: "Per person",
  },
  "salary-calculator": {
    annualSalary: "Annual salary",
    monthly: "Monthly",
    weekly: "Weekly",
    daily: "Daily",
    hourly: "Hourly",
  },
  "percentage-change-calculator": {
    originalValue: "Original value",
    newValue: "New value",
    percentageChange: "Percentage change",
    absoluteChange: "Absolute change: {change}",
  },
  "calorie-calculator": {
    age: "Age",
    gender: sharedEn.gender,
    weightKg: "Weight (kg)",
    heightCm: "Height (cm)",
    activityLevel: "Activity level",
    bmr: "BMR",
    tdee: "TDEE",
    loseWeight: "Lose weight",
    maintain: "Maintain",
    gainWeight: "Gain weight",
    loseWeightSub: "−500 cal",
    maintainSub: "TDEE",
    gainWeightSub: "+500 cal",
    activitySedentary: "Sedentary (little or no exercise)",
    activityLight: "Light (1–3 days/week)",
    activityModerate: "Moderate (3–5 days/week)",
    activityActive: "Active (6–7 days/week)",
    activityVeryActive: "Very active (physical job)",
  },
  "ideal-weight-calculator": {
    heightCm: "Height (cm)",
    gender: sharedEn.gender,
    recommendedRange: "Recommended range",
    formulaDevine: "Devine",
    formulaRobinson: "Robinson",
    formulaMiller: "Miller",
    formulaHamwi: "Hamwi",
  },
  "word-counter": {
    textLabel: "Text to analyze",
    textPlaceholder: "Start typing or paste your text here...",
    words: "Words",
    characters: "Characters",
    noSpaces: "No spaces",
    sentences: "Sentences",
    paragraphs: "Paragraphs",
    readingTime: "Reading time",
    readingLevel: "Reading level",
    difficulty: "Difficulty",
    limitTwitter: "Twitter",
    limitMeta: "Meta description",
    limitLinkedIn: "LinkedIn",
  },
  "character-counter": {
    textPlaceholder: "Type or paste your text here...",
    characters: "Characters",
    noSpaces: "No spaces",
    words: "Words",
    lines: "Lines",
  },
  "case-converter": {
    inputLabel: "Text to convert",
    inputPlaceholder: "Type or paste text here...",
    uppercase: "UPPERCASE",
    lowercase: "lowercase",
    titleCase: "Title Case",
    sentenceCase: "Sentence case",
    alternating: "Alternating",
    inverse: "Inverse Case",
    copy: sharedEn.copy,
    copied: sharedEn.copied,
    copyFailed: sharedEn.copyFailed,
  },
  "text-repeater": {
    textToRepeat: "Text to repeat",
    repeatCount: "Repeat count",
    separator: "Separator",
    output: "Output",
  },
  "lorem-ipsum-generator": {
    paragraphs: "Paragraphs",
    words: "Words",
    bytes: "Bytes",
    startWithLorem: "Start with \"Lorem ipsum\"",
    generate: "Generate",
    copy: sharedEn.copy,
  },
  "unit-converter": {
    value: sharedEn.value,
    from: sharedEn.from,
    to: sharedEn.to,
    result: sharedEn.result,
    categoryLength: "Length",
    categoryWeight: "Weight",
    categoryTemperature: "Temperature",
    categoryArea: "Area",
    categoryVolume: "Volume",
    categorySpeed: "Speed",
    categoryTime: "Time",
  },
  "hash-generator": {
    modeText: "Text",
    modeFile: "File",
    textPlaceholder: "Enter text to hash...",
    filePrompt: "Click or drag a file to hash",
    fileError: "Failed to read or hash the selected file.",
    algorithm: "Algorithm",
    hash: "Hash",
    filePromptAlt: "Drop or select a file to hash",
    computingHashes: "Computing hashes...",
    fileSize: "File size: {size} bytes",
  },
  "json-formatter": {
    inputLabel: "JSON input",
    outputLabel: "Output",
    format: "Format",
    minify: "Minify",
    validate: "Validate",
    copyOutput: "Copy output",
    validJson: "Valid JSON",
    invalidJson: "Invalid JSON",
  },
  "jwt-decoder": {
    tokenLabel: "JWT token",
    tokenPlaceholder: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
    header: "Header",
    payload: "Payload",
    signature: "Signature",
    invalidToken: "Invalid JWT token",
  },
  "color-converter": {
    hex: "HEX",
    rgb: "RGB",
    hsl: "HSL",
    pickColor: "Pick a color",
  },
  "color-palette-generator": {
    baseColor: "Base color",
    generate: "Generate palettes",
    copyHex: "Copy HEX",
    copied: sharedEn.copied,
    copyFailed: sharedEn.copyFailed,
  },
  "gradient-generator": {
    angle: "Angle",
    addColor: "Add color stop",
    removeColorStop: "Remove color stop",
    copyCss: "Copy CSS",
    cssOutput: "CSS output",
  },
  "regex-tester": {
    pattern: "Pattern",
    flags: "Flags",
    testString: "Test string",
    matches: "Matches",
    noMatches: "No matches",
    matchCount: "{count} matches",
    groups: "Groups",
  },
  "cron-expression-generator": {
    minute: "Minute",
    hour: "Hour",
    dayOfMonth: "Day of month",
    month: "Month",
    dayOfWeek: "Day of week",
    expression: "Expression",
    copyExpression: "Copy expression",
    nextRuns: "Next runs",
    description: "Description",
  },
  "markdown-editor": {
    editor: "Editor",
    preview: "Preview",
    copyMarkdown: "Copy Markdown",
    copyHtml: "Copy as HTML",
    toolbarBold: "Bold",
    toolbarItalic: "Italic",
    toolbarLink: "Link",
    toolbarImage: "Image",
    toolbarCode: "Code block",
    toolbarBullet: "Bullet list",
    toolbarNumbered: "Numbered list",
    toolbarHeading: "Heading",
  },
};

export const urToolUiMaps: Record<string, ToolUiMap> = {
  "simple-interest-calculator": {
    principal: "سرمایہ",
    rate: "شرح (%)",
    timeYears: "وقت (سال)",
    yearShort: "سال",
    interestEarned: "حاصل شدہ سود",
    totalAmount: "کل رقم",
  },
  "compound-interest-calculator": {
    principal: "سرمایہ",
    annualRate: "سالانہ شرح (%)",
    timeYears: "وقت (سال)",
    compounding: "مرکب سود",
    totalAmount: "کل رقم",
    totalInterest: "کل سود",
    yearByYearBreakdown: "سال بہ سال تفصیل",
    year: "سال",
    balance: "بیلنس",
    interestEarned: "حاصل شدہ سود",
    frequencyAnnually: "سالانہ",
    frequencySemiannually: "نصف سالانہ",
    frequencyQuarterly: "سہ ماہی",
    frequencyMonthly: "ماہانہ",
    frequencyDaily: "روزانہ",
  },
  "emi-calculator": {
    loanAmount: "قرض کی رقم",
    interestRate: "سود کی شرح (% سالانہ)",
    tenure: "مدت",
    monthlyEmi: "ماہانہ EMI",
    totalInterest: "کل سود",
    totalPayment: "کل ادائیگی",
    principalVsInterest: "سرمایہ بمقابلہ سود",
    principalPercent: "سرمایہ {percent}%",
    interestPercent: "سود {percent}%",
  },
  "bmi-calculator": {
    weight: "وزن",
    height: "قد",
    resultsAriaLabel: "BMI نتائج",
    yourBmiIs: "آپ کا BMI ہے",
    categoryUnderweight: "کم وزن",
    categoryNormal: "معمولی وزن",
    categoryOverweight: "زیادہ وزن",
    categoryObese: "موٹاپا",
  },
  "percentage-calculator": {
    tabOf: "X% کا Y",
    tabWhatPercent: "X، Y کا کتنا % ہے؟",
    tabChange: "% تبدیلی",
    labelPercentageX: "فیصد (X)",
    labelNumberY: "عدد (Y)",
    labelNumberX: "عدد (X)",
    labelFromX: "سے (X)",
    labelToY: "تک (Y)",
    resultOf: "{a}% کا {b} ہے {value}",
    resultWhatPercent: "{a}، {b} کا {value}% ہے",
    resultChange: "{a} سے {b} کی تبدیلی {value}% ہے",
  },
  "discount-calculator": {
    originalPrice: "اصل قیمت",
    discountPercent: "ڈسکاؤنٹ (%)",
    finalPrice: "حتمی قیمت",
    youSave: "آپ {amount} بچاتے ہیں",
  },
  "average-calculator": {
    numbersInput: "اعداد",
    numbersPlaceholder: "کوما یا نئی لائن سے الگ اعداد درج کریں...",
    mean: "میان",
    median: "درمیانی",
    mode: "موڈ",
    min: "کم",
    max: "زیادہ",
    count: "شمار",
    enterNumbers: "نتائج دیکھنے کے لیے کم از کم ایک درست عدد درج کریں۔",
  },
  "age-calculator": {
    dateOfBirth: "تاریخ پیدائش",
    asOfDate: "تاریخ تک",
    yourAge: "آپ کی عمر",
    years: "سال",
    months: "مہینے",
    days: "دن",
    livedSummary: "آپ {days} دن، یا تقریباً {hours} گھنٹے جی چکے ہیں۔",
    invalidDateRange:
      "براہ کرم ایک درست تاریخ پیدائش درج کریں جو \"تاریخ تک\" سے پہلے ہو۔",
    nextBirthdayIn: "اگلا سالگرہ {days} دن میں",
    nextBirthdayToday: "سالگرہ مبارک! آج آپ کی سالگرہ ہے۔",
    ageSummary: "{years} سال، {months} مہینے، {days} دن",
  },
  "tip-calculator": {
    billAmount: "بل کی رقم",
    tipPercent: "ٹپ (%)",
    people: "لوگ",
    tip: "ٹپ",
    total: "کل",
    perPerson: "فی شخص",
  },
  "salary-calculator": {
    annualSalary: "سالانہ تنخواہ",
    monthly: "ماہانہ",
    weekly: "ہفتہ وار",
    daily: "روزانہ",
    hourly: "گھنٹہ وار",
  },
  "percentage-change-calculator": {
    originalValue: "اصل قیمت",
    newValue: "نئی قیمت",
    percentageChange: "فیصد تبدیلی",
    absoluteChange: "مطلوب تبدیلی: {change}",
  },
  "calorie-calculator": {
    age: "عمر",
    gender: "جنس",
    weightKg: "وزن (kg)",
    heightCm: "قد (cm)",
    activityLevel: "سرگرمی کی سطح",
    bmr: "BMR",
    tdee: "TDEE",
    loseWeight: "وزن کم کریں",
    maintain: "برقرار رکھیں",
    gainWeight: "وزن بڑھائیں",
    loseWeightSub: "−500 cal",
    maintainSub: "TDEE",
    gainWeightSub: "+500 cal",
    activitySedentary: "بیہودہ (کم یا کوئی ورزش نہیں)",
    activityLight: "ہلکی (1–3 دن/ہفتہ)",
    activityModerate: "درمیانی (3–5 دن/ہفتہ)",
    activityActive: "فعال (6–7 دن/ہفتہ)",
    activityVeryActive: "بہت فعال (مشقت والا کام)",
  },
  "ideal-weight-calculator": {
    heightCm: "قد (cm)",
    gender: "جنس",
    recommendedRange: "تجویز کردہ حد",
    formulaDevine: "Devine",
    formulaRobinson: "Robinson",
    formulaMiller: "Miller",
    formulaHamwi: "Hamwi",
  },
  "hash-generator": {
    modeText: "ٹیکسٹ",
    modeFile: "فائل",
    textPlaceholder: "ہیش کرنے کے لیے ٹیکسٹ درج کریں...",
    filePrompt: "ہیش کرنے کے لیے فائل کلک یا ڈریگ کریں",
    fileError: "منتخب فائل پڑھنے یا ہیش کرنے میں ناکام۔",
    algorithm: "الگورتھم",
    hash: "ہیش",
    filePromptAlt: "ہیش کرنے کے لیے فائل ڈریگ یا منتخب کریں",
    computingHashes: "ہیشز کا حساب ہو رہا ہے...",
    fileSize: "فائل کا سائز: {size} bytes",
  },
};

export const esToolUiMaps: Record<string, ToolUiMap> = {
  "simple-interest-calculator": {
    principal: "Capital",
    rate: "Tasa (%)",
    timeYears: "Tiempo (años)",
    yearShort: "a",
    interestEarned: "Interés ganado",
    totalAmount: "Monto total",
  },
  "compound-interest-calculator": {
    principal: "Capital",
    annualRate: "Tasa anual (%)",
    timeYears: "Tiempo (años)",
    compounding: "Capitalización",
    totalAmount: "Monto total",
    totalInterest: "Interés total",
    yearByYearBreakdown: "Desglose año por año",
    year: "Año",
    balance: "Saldo",
    interestEarned: "Interés ganado",
    frequencyAnnually: "Anual",
    frequencySemiannually: "Semestral",
    frequencyQuarterly: "Trimestral",
    frequencyMonthly: "Mensual",
    frequencyDaily: "Diario",
  },
  "emi-calculator": {
    loanAmount: "Importe del préstamo",
    interestRate: "Tasa de interés (% anual)",
    tenure: "Plazo",
    monthlyEmi: "EMI mensual",
    totalInterest: "Interés total",
    totalPayment: "Pago total",
    principalVsInterest: "Capital vs interés",
    principalPercent: "Capital {percent}%",
    interestPercent: "Interés {percent}%",
  },
  "bmi-calculator": {
    weight: "Peso",
    height: "Altura",
    resultsAriaLabel: "Resultados de BMI",
    yourBmiIs: "Tu BMI es",
    categoryUnderweight: "Bajo peso",
    categoryNormal: "Peso normal",
    categoryOverweight: "Sobrepeso",
    categoryObese: "Obesidad",
  },
  "percentage-calculator": {
    tabOf: "X% de Y",
    tabWhatPercent: "¿X es qué % de Y?",
    tabChange: "% de cambio",
    labelPercentageX: "Porcentaje (X)",
    labelNumberY: "Número (Y)",
    labelNumberX: "Número (X)",
    labelFromX: "Desde (X)",
    labelToY: "Hasta (Y)",
    resultOf: "{a}% de {b} es {value}",
    resultWhatPercent: "{a} es {value}% de {b}",
    resultChange: "El cambio de {a} a {b} es {value}%",
  },
  "discount-calculator": {
    originalPrice: "Precio original",
    discountPercent: "Descuento (%)",
    finalPrice: "Precio final",
    youSave: "Ahorras {amount}",
  },
  "average-calculator": {
    numbersInput: "Números",
    numbersPlaceholder: "Introduce números separados por comas o líneas...",
    mean: "Media",
    median: "Mediana",
    mode: "Moda",
    min: "Mín",
    max: "Máx",
    count: "Cantidad",
    enterNumbers: "Introduce al menos un número válido para ver resultados.",
  },
  "age-calculator": {
    dateOfBirth: "Fecha de nacimiento",
    asOfDate: "Fecha de referencia",
    yourAge: "Tu edad",
    years: "Años",
    months: "Meses",
    days: "Días",
    livedSummary: "Has vivido {days} días, o aproximadamente {hours} horas.",
    invalidDateRange:
      "Introduce una fecha de nacimiento válida anterior a la fecha de referencia.",
    nextBirthdayIn: "Próximo cumpleaños en {days} días",
    nextBirthdayToday: "¡Feliz cumpleaños! Hoy es tu cumpleaños.",
    ageSummary: "{years} años, {months} meses, {days} días",
  },
  "tip-calculator": {
    billAmount: "Importe del bill",
    tipPercent: "Propina (%)",
    people: "Personas",
    tip: "Propina",
    total: "Total",
    perPerson: "Por persona",
  },
  "salary-calculator": {
    annualSalary: "Salario anual",
    monthly: "Mensual",
    weekly: "Semanal",
    daily: "Diario",
    hourly: "Por hora",
  },
  "percentage-change-calculator": {
    originalValue: "Valor original",
    newValue: "Valor nuevo",
    percentageChange: "Cambio porcentual",
    absoluteChange: "Cambio absoluto: {change}",
  },
  "calorie-calculator": {
    age: "Edad",
    gender: "Género",
    weightKg: "Peso (kg)",
    heightCm: "Altura (cm)",
    activityLevel: "Nivel de actividad",
    bmr: "BMR",
    tdee: "TDEE",
    loseWeight: "Perder peso",
    maintain: "Mantener",
    gainWeight: "Ganar peso",
    loseWeightSub: "−500 cal",
    maintainSub: "TDEE",
    gainWeightSub: "+500 cal",
    activitySedentary: "Sedentario (poco o nada de ejercicio)",
    activityLight: "Ligero (1–3 días/semana)",
    activityModerate: "Moderado (3–5 días/semana)",
    activityActive: "Activo (6–7 días/semana)",
    activityVeryActive: "Muy activo (trabajo físico)",
  },
  "ideal-weight-calculator": {
    heightCm: "Altura (cm)",
    gender: "Género",
    recommendedRange: "Rango recomendado",
    formulaDevine: "Devine",
    formulaRobinson: "Robinson",
    formulaMiller: "Miller",
    formulaHamwi: "Hamwi",
  },
  "hash-generator": {
    modeText: "Texto",
    modeFile: "Archivo",
    textPlaceholder: "Introduce texto para hashear...",
    filePrompt: "Haz clic o arrastra un archivo para hashear",
    fileError: "No se pudo leer o hashear el archivo seleccionado.",
    algorithm: "Algoritmo",
    hash: "Hash",
    filePromptAlt: "Arrastra o selecciona un archivo para hashear",
    computingHashes: "Calculando hashes...",
    fileSize: "Tamaño del archivo: {size} bytes",
  },
};
